name: Docker Push

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Docker Compose
        run: sudo apt -y update && sudo apt -y install docker-compose

      - name: Docker build
        run: docker-compose build

      - name: Docker push
        run: docker push tmvdl/python -a
